package com.example.airesume.ai;

public enum PromptType {
    JD_ANALYSIS,
    OPTIMIZATION_DIFF,
    INTERVIEW_QUESTION,
    INTERVIEW_FEEDBACK,
    COVER_LETTER,
    AI_CHAT,
    RESUME_GENERATE,
    RESUME_PARSE,
    JD_MATCH,
    GRAMMAR_CHECK,
    COVER_LETTER_GENERATE,
    TRANSLATE,
    SECTION_OPTIMIZE,
    QUALITY_SCORE,
    DOCX_PARSE
}
